name: embedding_poc
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.1.0
  - pytorch-cuda=12.1
  - pip
  - pip:
    # Core dependencies
    - fastapi>=0.104.0
    - uvicorn[standard]>=0.24.0
    - pydantic>=2.5.0
    - tyro>=0.6.0

    # HuggingFace/LangChain backend
    - langchain>=0.1.0
    - langchain-community>=0.0.10
    - sentence-transformers>=2.2.0
    - transformers>=4.36.0

    # ONNX Runtime + TensorRT backend
    - onnxruntime-gpu>=1.16.0
    - optimum[onnxruntime-gpu]>=1.14.0

    # Testing and metrics
    - httpx>=0.25.0
    - numpy>=1.24.0
    - datasets>=2.15.0

    # Monitoring
    - psutil>=5.9.0
    - pynvml>=11.5.0

    # Logging
    - structlog>=23.2.0
    - colorama>=0.4.6

    # Visualization
    - matplotlib>=3.8.0
    - seaborn>=0.13.0
